### ISSUE TITLE
Gateway

### ISSUE THREAD

**Issue by akiicat** [ECG-IoT-System/progress#2]
- [x] [ecg receiver](https://github.com/akiicat/ecg-receiver) 安裝在 raspberry pi 的說明文件
- [x] 開機自動執行 ecg receiver 的說明文件

**Comment by akizukisuki** [comment]
你好~
我是劉晉瑋
以下是這次報告的連結
https://hackmd.io/s/SkShX8AFm

**Comment by akizukisuki** [comment]
學長，想請問在app.js中是如何印出關於收到的資料
因為我看程式碼中在
noble.stopScanning 後的console.log
似乎也不是印出那些資料

**Comment by akiicat** [comment]
@akizukisuki 要使用 `>` 這個符號或是 `>>` 這個符號，把螢幕上的訊息輸出到一個檔案裡
這個[章節 10.5.1](http://linux.vbird.org/linux_basic/0320bash.php#redirect)有詳細的介紹
